
# This task creates the DHCP configuration file by using a Jinja2 template.
# The template file (dhcpd.conf.j2) is processed and the result is saved to
# the specified destination path (/etc/dhcp/dhcpd.conf).
- name: Create DHCP configuration file
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf



