- name: Create HAProxy configuration file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

#- name: Enable and start HAProxy service
#  ansible.builtin.service:
#    name: haproxy
#    state: started
#    enabled: yes
